import type {
  GuildConfig,
  RecoveryOffer,
  Scenario,
  Tier,
  TierPurchasePolicy,
} from './types'

const SUPPLY_PRIORITY = [
  'ad-or-diamond-ad',
  'ad-or-diamond-diamond',
  'flyer',
  'cheer-stick',
  'instant-2000',
  'instant-1000',
  'instant-600',
]

const createPurchasePolicy = (): TierPurchasePolicy => ({
  dailyUsdBudget: 0,
  dailyDiamondBudget: 0,
  useAds: false,
  supplyPriority: [...SUPPLY_PRIORITY],
})

const offers: RecoveryOffer[] = [
  {
    id: 'flyer',
    label: '宣传单',
    mode: 'program',
    usdCost: 0.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0.5,
    pulseCapacityRates: [{ afterMinutes: 10, rate: 0.5 }],
    continuousCapacityRate: 0,
    durationMinutes: 10,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'cheer-stick',
    label: '应援棒',
    mode: 'program',
    usdCost: 2.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 1,
    pulseCapacityRates: [
      { afterMinutes: 10, rate: 1 },
      { afterMinutes: 20, rate: 1 },
      { afterMinutes: 30, rate: 1 },
    ],
    continuousCapacityRate: 0,
    durationMinutes: 30,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'ad-or-diamond-ad',
    label: '奖励广告恢复',
    mode: 'program',
    usdCost: 0,
    diamondCost: 0,
    adCost: 1,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0.5,
    durationMinutes: 30,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'ad-or-diamond-diamond',
    label: '钻石恢复',
    mode: 'program',
    usdCost: 0,
    diamondCost: 20,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0.5,
    durationMinutes: 30,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'instant-600',
    label: '即时补给 600',
    mode: 'instant',
    usdCost: 2.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0,
    durationMinutes: 0,
    fixedFans: 600,
    dailyPurchaseLimit: null,
  },
  {
    id: 'instant-1000',
    label: '即时补给 1,000',
    mode: 'instant',
    usdCost: 5.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0,
    durationMinutes: 0,
    fixedFans: 1000,
    dailyPurchaseLimit: null,
  },
  {
    id: 'instant-2000',
    label: '即时补给 2,000',
    mode: 'instant',
    usdCost: 9.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0,
    durationMinutes: 0,
    fixedFans: 2000,
    dailyPurchaseLimit: null,
  },
]

const guildDefaults = (
  id: string,
  name: string,
  roster: Record<Tier, number>,
): GuildConfig => ({
  id,
  name,
  roster,
  deployFans: { normal: 1000, core: 1500, center: 2000 },
  priorities: { normal: 1, core: 2, center: 3 },
})

export const DEFAULT_SCENARIO: Scenario = {
  battle: {
    baseIdolPower: 100_000,
    tierMultipliers: { normal: 1, small: 3, whale: 9 },
    alpha: 1.36,
    beta: 2,
    randomMin: 0.9,
    randomMax: 1.1,
    styleAdvantage: 0.03,
    calibrationStyle: 'neutral',
    homeLossFactor: 0.8,
    lossBands: [
      { minRatio: 1.3, rate: 0.1 },
      { minRatio: 1.1, rate: 0.1 },
      { minRatio: 0.9, rate: 0.2 },
      { minRatio: 0.7, rate: 0.1 },
      { minRatio: 0, rate: 0.3 },
    ],
  },
  fans: {
    capacity: 2000,
    minDeploy: 1000,
    maxDeploy: 2000,
    naturalCapacityPerDay: 1,
    attackCooldownMinutes: 10,
    formationSlots: 999,
    dailyActionLimit: null,
  },
  score: {
    attackWinBase: 10,
    attackLoss: 3,
    holdPerHourBase: 0.5,
    nodeMultipliers: { normal: 1, core: 2, center: 3 },
    defenderPersonalWinBase: 5,
    defenderPersonalLoss: 2,
    defenderPersonalDailyCap: 2,
  },
  supply: {
    offers,
    adDailyLimit: 3,
    diamondUsdRate: null,
    purchasePolicies: {
      normal: createPurchasePolicy(),
      small: createPurchasePolicy(),
      whale: createPurchasePolicy(),
    },
  },
  season: {
    days: 6,
    centerUnlockDay: 6,
    nodeCounts: { normal: 32, core: 8, center: 1 },
  },
  guilds: [
    guildDefaults('A', '公会 A', { normal: 10, small: 0, whale: 1 }),
    guildDefaults('B', '公会 B', { normal: 10, small: 1, whale: 0 }),
    guildDefaults('C', '公会 C', { normal: 20, small: 0, whale: 0 }),
    guildDefaults('D', '公会 D', { normal: 10, small: 0, whale: 0 }),
  ],
  simulation: {
    runs: 1000,
    seed: 20_260_924,
    maxEventsPerDay: 100_000,
  },
}
