import type {
  BattleFormulaConfig,
  GuildConfig,
  RecoveryOffer,
  Scenario,
  Tier,
  TierPurchasePolicy,
  RewardConfig,
} from './types'

export const DEFAULT_BATTLE_FORMULAS: BattleFormulaConfig = {
  preRandomPower: 'idolPower <= 0 || initialFans <= 0 || currentFans <= 0 || styleMultiplier <= 0 ? 0 : idolPower * pow(initialFans / 1000, alpha) * pow(currentFans / initialFans, beta) * styleMultiplier',
  displayedTendency: 'attackerPower + defenderPower > 0 ? attackerPower / (attackerPower + defenderPower) : 0.5',
  winProbability: 'uniformWinProbability(attackerPower, defenderPower, randomMin, randomMax)',
  fanLoss: 'round(currentFans * lossBandRate * sideLossFactor)',
}

const SUPPLY_PRIORITY = [
  'ad-or-diamond-ad',
  'ad-or-diamond-diamond',
  'flyer',
  'cheer-stick',
  'instant-2000',
  'instant-1000',
  'instant-600',
]

const PAID_SUPPLY_PRIORITY = [
  'flyer',
  'cheer-stick',
  'instant-2000',
  'instant-1000',
  'instant-600',
  'ad-or-diamond-ad',
  'ad-or-diamond-diamond',
]

const createPurchasePolicy = (tier: Tier): TierPurchasePolicy => ({
  versionUsdBudget: tier === 'normal' ? 0 : tier === 'small' ? 24 : 90,
  versionDiamondBudget: tier === 'normal' ? 120 : 0,
  versionAdBudget: tier === 'normal' ? 12 : 0,
  useAds: tier === 'normal',
  supplyPriority: [...(tier === 'normal' ? SUPPLY_PRIORITY : PAID_SUPPLY_PRIORITY)],
})

const offers: RecoveryOffer[] = [
  {
    id: 'flyer',
    label: '宣传单',
    mode: 'program',
    usdCost: 0.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0.5,
    pulseCapacityRates: [{ afterMinutes: 10, rate: 0.5 }],
    continuousCapacityRate: 0,
    durationMinutes: 10,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'cheer-stick',
    label: '应援棒',
    mode: 'program',
    usdCost: 2.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 1,
    pulseCapacityRates: [
      { afterMinutes: 10, rate: 1 },
      { afterMinutes: 20, rate: 1 },
      { afterMinutes: 30, rate: 1 },
    ],
    continuousCapacityRate: 0,
    durationMinutes: 30,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'ad-or-diamond-ad',
    label: '奖励广告恢复',
    mode: 'program',
    usdCost: 0,
    diamondCost: 0,
    adCost: 1,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0.5,
    durationMinutes: 30,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'ad-or-diamond-diamond',
    label: '钻石恢复',
    mode: 'program',
    usdCost: 0,
    diamondCost: 20,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0.5,
    durationMinutes: 30,
    fixedFans: 0,
    dailyPurchaseLimit: null,
  },
  {
    id: 'instant-600',
    label: '即时补给 600',
    mode: 'instant',
    usdCost: 2.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0,
    durationMinutes: 0,
    fixedFans: 600,
    dailyPurchaseLimit: null,
  },
  {
    id: 'instant-1000',
    label: '即时补给 1,000',
    mode: 'instant',
    usdCost: 5.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0,
    durationMinutes: 0,
    fixedFans: 1000,
    dailyPurchaseLimit: null,
  },
  {
    id: 'instant-2000',
    label: '即时补给 2,000',
    mode: 'instant',
    usdCost: 9.99,
    diamondCost: 0,
    adCost: 0,
    immediateCapacityRate: 0,
    pulseCapacityRates: [],
    continuousCapacityRate: 0,
    durationMinutes: 0,
    fixedFans: 2000,
    dailyPurchaseLimit: null,
  },
]

const guildDefaults = (
  id: string,
  name: string,
  roster: Record<Tier, number>,
): GuildConfig => ({
  id,
  name,
  roster,
  purchasePolicies: {
    normal: createPurchasePolicy('normal'),
    small: createPurchasePolicy('small'),
    whale: createPurchasePolicy('whale'),
  },
  deployFans: { normal: 1000, core: 1500, center: 2000 },
  priorities: { normal: 1, core: 2, center: 3 },
})

export const DEFAULT_REWARD_CONFIG: RewardConfig = {
  targetPoints: 110_000,
  dailyPointCap: 22_000,
  rankMinActiveDays: 3,
  rankMinProgressRate: 0.4,
  personalStages: [
    { points: 1_000, rewards: [{ resourceId: 90, quantity: 20 }] },
    { points: 5_600, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }] },
    { points: 10_000, rewards: [{ resourceId: 90, quantity: 20 }, { resourceId: 91, quantity: 20 }] },
    { points: 18_900, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }, { resourceId: 90, quantity: 20 }] },
    { points: 25_500, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }] },
    { points: 35_500, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 90, quantity: 20 }, { resourceId: 91, quantity: 20 }] },
    { points: 43_700, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }, { resourceId: 90, quantity: 20 }] },
    { points: 56_200, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }] },
    { points: 66_100, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 90, quantity: 20 }, { resourceId: 91, quantity: 20 }] },
    { points: 81_000, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }, { resourceId: 90, quantity: 20 }] },
    { points: 92_600, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 10 }, { resourceId: 90, quantity: 20 }] },
    { points: 110_000, rewards: [{ resourceId: 2, quantity: 20 }, { resourceId: 5, quantity: 20 }, { resourceId: 90, quantity: 40 }, { resourceId: 91, quantity: 20 }] },
  ],
  guildMilestones: [
    { completionRate: 0.2, minimumPersonalRate: 0.1, rewards: [{ resourceId: 2, quantity: 10 }, { resourceId: 90, quantity: 10 }] },
    { completionRate: 0.4, minimumPersonalRate: 0.2, rewards: [{ resourceId: 2, quantity: 10 }, { resourceId: 5, quantity: 10 }, { resourceId: 90, quantity: 10 }] },
    { completionRate: 0.6, minimumPersonalRate: 0.3, rewards: [{ resourceId: 2, quantity: 10 }, { resourceId: 90, quantity: 10 }, { resourceId: 91, quantity: 10 }] },
    { completionRate: 0.8, minimumPersonalRate: 0.4, rewards: [{ resourceId: 2, quantity: 10 }, { resourceId: 5, quantity: 10 }, { resourceId: 90, quantity: 10 }, { resourceId: 91, quantity: 10 }] },
  ],
  rankRewards: [
    { rank: 1, merit: 20, titleId: null, titleLabel: '冠军聊天称号' },
    { rank: 2, merit: 15, titleId: null, titleLabel: '亚军聊天称号' },
    { rank: 3, merit: 10, titleId: null, titleLabel: '季军聊天称号' },
    { rank: 4, merit: 5, titleId: null, titleLabel: '参赛聊天称号' },
  ],
  legacyProgressThreshold: 664_000,
  legacyFreeMode: 'replace',
}

export const DEFAULT_SCENARIO: Scenario = {
  battle: {
    formulas: { ...DEFAULT_BATTLE_FORMULAS },
    baseIdolPower: 100_000,
    tierMultipliers: { normal: 1, small: 3, whale: 9 },
    alpha: 1.36,
    beta: 2,
    randomMin: 0.9,
    randomMax: 1.1,
    styleAdvantage: 0.03,
    calibrationStyle: 'neutral',
    homeLossFactor: 0.8,
    lossBands: [
      { minRatio: 1.3, rate: 0.1 },
      { minRatio: 1.1, rate: 0.1 },
      { minRatio: 0.9, rate: 0.2 },
      { minRatio: 0.7, rate: 0.1 },
      { minRatio: 0, rate: 0.3 },
    ],
  },
  fans: {
    capacity: 2000,
    minDeploy: 1000,
    maxDeploy: 2000,
    naturalCapacityPerDay: 1,
    attackCooldownMinutes: 10,
    formationSlots: 999,
    dailyActionLimit: null,
  },
  score: {
    attackWinBase: 10,
    attackLoss: 3,
    holdPerHourBase: 0.5,
    nodeMultipliers: { normal: 1, core: 2, center: 3 },
    defenderPersonalWinBase: 5,
    defenderPersonalLoss: 2,
    defenderPersonalDailyCap: 2,
  },
  supply: {
    offers,
    adDailyLimit: 3,
    diamondUsdRate: null,
  },
  season: {
    days: 6,
    centerUnlockDay: 6,
    nodeCounts: { normal: 32, core: 8, center: 1 },
  },
  guilds: [
    guildDefaults('A', '公会 A', { normal: 10, small: 0, whale: 1 }),
    guildDefaults('B', '公会 B', { normal: 10, small: 1, whale: 0 }),
    guildDefaults('C', '公会 C', { normal: 20, small: 0, whale: 0 }),
    guildDefaults('D', '公会 D', { normal: 10, small: 0, whale: 0 }),
  ],
  rewards: structuredClone(DEFAULT_REWARD_CONFIG),
  simulation: {
    runs: 1000,
    seed: 20_260_924,
    maxEventsPerDay: 100_000,
  },
}
